-- INSERT INTO Student VALUES(1, '47G23g7g', 'Perman', 'Atayev', 'atayev@harvard.edu', 'CS', 0, 10000,'2020-01-20');
-- INSERT INTO Instructor VALUES();
-- INSERT INTO TA VALUES();

-- Courses
-- Sections
-- Prereq
-- Classroom
-- Department
-- Assists
-- Career